[book]
authors = ["Ali Gottschall", "João Pereira"]
language = "en"
multilingual = false
src = "src"
title = "Practical Program Verification in Go with Gobra (alpha)"

[output.html]
theme = "theme"
additional-js = [
              "dist/code/gobra-book.js",
              "mode-golang.js",
              "mode-gobra.js",
              ]
mathjax-support = true

[output.html.playground]
editable = true
copy-js = true

[preprocessor.quiz]

[output.linkcheck]
warning-policy = "ignore"
