[book]
authors = ["Ali Gottschall", "João Pereira"]
language = "en"
multilingual = false
src = "src"
title = "The Gobra Book"
description = "Formally Verifying Go Programs with Gobra"

[output.html]
mathjax-support = true

[output.html.code.hidelines]
gobra = "~"
go    = "~"
