[book]
authors = ["Ali Gottschall", "João Pereira"]
language = "en"
multilingual = false
src = "src"
title = "Practical Program Verification in Go with Gobra (alpha)"

[output.html]
theme = "theme"
mathjax-support = true

[output.html.playground]
editable = true
copy-js = true

[output.html.code.hidelines]
gobra = "~"
go    = "~"

[preprocessor.quiz]
